import { StyleSheet } from 'react-native';

import { colors } from '../../theme/colors';
import { spacing } from '../../theme/spacing';

export function createChatRoomStyles() {
  return StyleSheet.create({
  addSubscribersButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 22,
    flexDirection: 'row',
    gap: spacing.xs,
    justifyContent: 'center',
    marginTop: spacing.md,
    minHeight: 44,
  },
  addSubscribersButtonDisabled: {
    opacity: 0.45,
  },
  addSubscribersButtonText: {
    color: colors.white,
    fontSize: 15,
    fontWeight: '900',
  },
  composer: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    gap: spacing.sm,
    padding: spacing.sm,
  },
  composerKeyboardAvoider: {
    width: '100%',
  },
  composerKeyboardAvoiderContent: {
    width: '100%',
  },
  addContactPrompt: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  addContactPromptPrimary: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 36,
    minWidth: 64,
    paddingHorizontal: spacing.md,
  },
  addContactPromptPrimaryText: {
    color: colors.white,
    fontSize: 13,
    fontWeight: '900',
  },
  addContactPromptSecondary: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: spacing.sm,
  },
  addContactPromptSecondaryText: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '800',
  },
  addContactPromptSubtitle: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  addContactPromptText: {
    flex: 1,
    minWidth: 0,
  },
  addContactPromptTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '900',
  },
  voiceRoomAdminMuteButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  voiceRoomAdminMuteButtonActive: {
    backgroundColor: colors.danger,
  },
  voiceRoomCloseButton: {
    alignItems: 'center',
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  voiceRoomControlButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  voiceRoomControlButtonActive: {
    backgroundColor: colors.danger,
  },
  voiceRoomControlButtonDisabled: {
    opacity: 0.45,
  },
  voiceRoomControls: {
    alignItems: 'center',
    backgroundColor: colors.appBackground,
    borderTopColor: colors.border,
    borderTopWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  voiceRoomLoadMoreButton: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
  },
  voiceRoomLoadMoreText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '900',
  },
  voiceRoomModalBackdrop: {
    backgroundColor: 'rgba(0,0,0,0.55)',
    flex: 1,
    justifyContent: 'flex-end',
    padding: spacing.md,
  },
  voiceRoomModalTitle: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: 18,
    fontWeight: '900',
  },
  voiceRoomPeopleButton: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.xs,
    height: 36,
    justifyContent: 'center',
    paddingHorizontal: spacing.sm,
  },
  voiceRoomPeopleHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    paddingBottom: spacing.sm,
  },
  voiceRoomPeopleName: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '900',
  },
  voiceRoomPeoplePanel: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    maxHeight: '78%',
    padding: spacing.md,
  },
  voiceRoomPeopleRow: {
    alignItems: 'center',
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.md,
    minHeight: 62,
  },
  voiceRoomPeopleSubtitle: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 2,
  },
  voiceRoomPeopleText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '900',
  },
  voiceRoomPeopleTextWrap: {
    flex: 1,
  },
  voiceRoomPushToTalkButton: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 24,
    borderWidth: StyleSheet.hairlineWidth,
    height: 48,
    justifyContent: 'center',
    marginLeft: 'auto',
    width: 48,
  },
  voiceRoomPushToTalkButtonActive: {
    borderColor: colors.primary,
  },
  voiceRoomPushToTalkButtonHolding: {
    backgroundColor: colors.primary,
  },
  voiceRoomPushToTalkText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '900',
  },
  voiceRoomRoutePanel: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    gap: spacing.xs,
    padding: spacing.md,
  },
  voiceRoomRouteRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    minHeight: 50,
  },
  voiceRoomRouteText: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
  },
  voiceRoomStatus: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.xs,
    justifyContent: 'center',
    minWidth: 18,
  },
  voiceRoomStatusLight: {
    borderRadius: 6,
    height: 12,
    width: 12,
  },
  voiceRoomStatusLightOffline: {
    backgroundColor: colors.danger,
  },
  voiceRoomStatusLightOnline: {
    backgroundColor: '#22c55e',
  },
  captionBackdrop: {
    backgroundColor: 'rgba(0,0,0,0.42)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  captionFileMeta: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '700',
    marginTop: 2,
  },
  captionFileName: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '900',
  },
  captionFilePreview: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 12,
    flexDirection: 'row',
    gap: spacing.md,
    padding: spacing.md,
  },
  captionFileText: {
    flex: 1,
  },
  captionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  captionHeaderActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  captionImagePreview: {
    alignSelf: 'center',
    aspectRatio: 1,
    backgroundColor: colors.border,
    borderRadius: 12,
    width: '72%',
  },
  captionInput: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: 16,
    maxHeight: 110,
    minHeight: 44,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  captionInputRow: {
    alignItems: 'flex-end',
    backgroundColor: colors.surface,
    borderRadius: 24,
    flexDirection: 'row',
    gap: spacing.xs,
    paddingLeft: spacing.xs,
  },
  captionPanel: {
    backgroundColor: colors.appBackground,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    gap: spacing.md,
    padding: spacing.lg,
    zIndex: 1,
  },
  captionSendButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  captionTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '900',
  },
  captionToolButton: {
    alignItems: 'center',
    backgroundColor: colors.outgoingBubble,
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  drawingButtonDisabled: {
    opacity: 0.45,
  },
  drawingCanvas: {
    backgroundColor: '#000000',
    borderRadius: 8,
    overflow: 'hidden',
  },
  drawingCanvasWrap: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
  },
  drawingColorRail: {
    borderRadius: 999,
    height: 24,
  },
  drawingColorRailWrap: {
    justifyContent: 'center',
    minHeight: 44,
  },
  drawingColorThumb: {
    borderColor: colors.white,
    borderRadius: 12,
    borderWidth: 3,
    height: 24,
    position: 'absolute',
    shadowColor: '#000000',
    shadowOffset: { height: 2, width: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    width: 24,
  },
  drawingHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  drawingHeaderActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  drawingIconButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderRadius: 20,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  drawingScreen: {
    backgroundColor: '#000000',
    flex: 1,
  },
  drawingSendButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 20,
    justifyContent: 'center',
    minHeight: 40,
    minWidth: 76,
    paddingHorizontal: spacing.md,
  },
  drawingSendText: {
    color: colors.white,
    fontSize: 15,
    fontWeight: '900',
  },
  drawingTitle: {
    color: colors.white,
    flex: 1,
    fontSize: 17,
    fontWeight: '900',
    textAlign: 'center',
  },
  drawingToolLabel: {
    color: colors.white,
    fontSize: 13,
    fontWeight: '800',
  },
  drawingTools: {
    gap: spacing.sm,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
  },
  editMessageActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'flex-end',
  },
  editMessageButtonDisabled: {
    opacity: 0.55,
  },
  editMessageInput: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    color: colors.textPrimary,
    fontSize: 16,
    maxHeight: 180,
    minHeight: 110,
    padding: spacing.md,
    textAlignVertical: 'top',
  },
  editMessageKeyboardAvoider: {
    flex: 1,
  },
  editMessagePrimaryButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 18,
    minHeight: 40,
    minWidth: 92,
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  editMessagePrimaryText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '900',
  },
  editMessageSecondaryButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    minHeight: 40,
    minWidth: 92,
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  editMessageSecondaryText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '900',
  },
  voiceEffectActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  voiceEffectList: {
    gap: spacing.xs,
    marginTop: spacing.sm,
  },
  voiceEffectOption: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.sm,
    minHeight: 56,
    paddingHorizontal: spacing.sm + spacing.xs,
    paddingVertical: spacing.xs,
  },
  voiceEffectOptionDescription: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
    marginTop: 2,
  },
  voiceEffectOptionDescriptionSelected: {
    color: 'rgba(255,255,255,0.84)',
  },
  voiceEffectOptionIcon: {
    alignItems: 'center',
    backgroundColor: colors.outgoingBubble,
    borderRadius: 16,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  voiceEffectOptionSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  voiceEffectOptionText: {
    flex: 1,
  },
  voiceEffectOptionTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '800',
  },
  voiceEffectOptionTitleSelected: {
    color: colors.white,
  },
  voiceEffectPanel: {
    backgroundColor: colors.appBackground,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
  },
  voiceEffectPrimaryButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 10,
    flex: 1,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: spacing.md,
  },
  voiceEffectPrimaryButtonDisabled: {
    opacity: 0.65,
  },
  voiceEffectPrimaryButtonText: {
    color: colors.white,
    fontSize: 15,
    fontWeight: '900',
  },
  voiceEffectSecondaryButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    flex: 1,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: spacing.md,
  },
  voiceEffectSecondaryButtonText: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '800',
  },
  voiceEffectSubtitle: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 16,
    marginTop: 4,
  },
  voiceEffectTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '900',
  },
  iconButton: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 24,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  iconButtonActive: {
    backgroundColor: colors.primary,
  },
  iconButtonDisabled: {
    opacity: 0.45,
  },
  headerActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.xs,
  },
  emojiButton: {
    alignItems: 'center',
    borderRadius: 8,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  emojiGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
    padding: spacing.sm,
  },
  emojiPanel: {
    backgroundColor: colors.appBackground,
    borderTopColor: colors.border,
    borderTopWidth: StyleSheet.hairlineWidth,
    maxHeight: 260,
  },
  emojiTab: {
    alignItems: 'center',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  emojiTabActive: {
    backgroundColor: colors.primary,
  },
  emojiTabs: {
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  emojiText: {
    fontSize: 27,
  },
  headerButton: {
    alignItems: 'center',
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  headerTitleButton: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    maxWidth: 210,
  },
  headerTitleContent: {
    flex: 1,
    minWidth: 0,
  },
  headerTitleLine: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.xs,
    minWidth: 0,
  },
  headerSubtitleText: {
    color: 'rgba(255,255,255,0.82)',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 1,
  },
  headerTitleText: {
    color: colors.white,
    flexShrink: 1,
    fontSize: 18,
    fontWeight: '800',
  },
  actionBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.28)',
    flex: 1,
    justifyContent: 'center',
    padding: spacing.xl,
  },
  actionButton: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    minHeight: 48,
    paddingHorizontal: spacing.md,
  },
  actionButtonText: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: 16,
    fontWeight: '800',
  },
  actionButtonTextDanger: {
    color: colors.danger,
  },
  actionPanel: {
    backgroundColor: colors.appBackground,
    borderRadius: 12,
    padding: spacing.sm,
    width: '100%',
  },
  actionTitle: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '900',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  sendOptionsForm: {
    gap: spacing.md,
    padding: spacing.md,
  },
  sendOptionsHint: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  sendOptionsInput: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 10,
    borderWidth: 1,
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '800',
    minHeight: 46,
    paddingHorizontal: spacing.md,
  },
  sendOptionsPanel: {
    backgroundColor: colors.appBackground,
    borderRadius: 12,
    padding: spacing.sm,
    width: '100%',
  },
  sendOptionsTimeRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  smallTimeInput: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 10,
    borderWidth: 1,
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '900',
    minHeight: 46,
    paddingHorizontal: spacing.sm,
    textAlign: 'center',
  },
  smallTimeInputLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '800',
  },
  smallTimeInputWrap: {
    flex: 1,
    gap: spacing.xs,
  },
  reactionQuickButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  reactionQuickButtonActive: {
    backgroundColor: colors.outgoingBubble,
    borderColor: colors.primary,
  },
  reactionQuickEmoji: {
    fontSize: 22,
  },
  reactionQuickRow: {
    flexDirection: 'row',
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  addSubscribersOverlay: {
    backgroundColor: 'rgba(0,0,0,0.5)',
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    zIndex: 10,
  },
  pinnedBanner: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.sm,
    minHeight: 50,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  pinnedBannerIcon: {
    alignItems: 'center',
    backgroundColor: colors.outgoingBubble,
    borderRadius: 16,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  pinnedBannerPressed: {
    opacity: 0.78,
  },
  pinnedBannerPreview: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '800',
  },
  pinnedBannerText: {
    flex: 1,
    minWidth: 0,
  },
  pinnedBannerTitle: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  pinnedEmptyText: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: '700',
    paddingVertical: spacing.xl,
    textAlign: 'center',
  },
  pinnedList: {
    marginTop: spacing.sm,
    maxHeight: 420,
  },
  pinnedModalBackdrop: {
    backgroundColor: 'rgba(0,0,0,0.34)',
    flex: 1,
    justifyContent: 'center',
    padding: spacing.lg,
  },
  pinnedModalClose: {
    alignItems: 'center',
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  pinnedModalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  pinnedModalPanel: {
    backgroundColor: colors.appBackground,
    borderRadius: 18,
    maxHeight: '78%',
    padding: spacing.md,
  },
  pinnedModalTitle: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: 18,
    fontWeight: '900',
  },
  pinnedRow: {
    alignItems: 'center',
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    minHeight: 58,
  },
  pinnedRowMain: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: spacing.sm,
    paddingVertical: spacing.sm,
  },
  pinnedRowDate: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: '700',
  },
  pinnedRowMeta: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
    marginTop: 3,
  },
  pinnedRowPressed: {
    backgroundColor: colors.surface,
  },
  pinnedRowText: {
    flex: 1,
    minWidth: 0,
  },
  pinnedRowTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '900',
  },
  pinnedRemoveButton: {
    alignItems: 'center',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  pinnedScopeBadge: {
    backgroundColor: colors.outgoingBubble,
    borderRadius: 9,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  pinnedScopeBadgeText: {
    color: colors.primary,
    fontSize: 10,
    fontWeight: '900',
  },
  pinnedSearchInput: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: 15,
    minHeight: 40,
    padding: 0,
  },
  pinnedSearchWrap: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  pinnedThumb: {
    backgroundColor: colors.surface,
    borderRadius: 8,
    height: 42,
    overflow: 'hidden',
    position: 'relative',
    width: 42,
  },
  pinnedThumbIcon: {
    alignItems: 'center',
    backgroundColor: colors.outgoingBubble,
    borderRadius: 8,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  pinnedThumbImage: {
    height: '100%',
    width: '100%',
  },
  pinnedThumbOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.42)',
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  composerReply: {
    backgroundColor: colors.surface,
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderLeftColor: colors.primary,
    borderLeftWidth: 3,
    flexDirection: 'row',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  composerReplyBody: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 17,
  },
  composerReplyClose: {
    alignItems: 'center',
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  composerReplyText: {
    flex: 1,
  },
  composerReplyTitle: {
    color: colors.primaryDark,
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 1,
  },
  forwardClose: {
    alignItems: 'center',
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  forwardDivider: {
    backgroundColor: colors.border,
    height: StyleSheet.hairlineWidth,
    marginVertical: spacing.sm,
  },
  forwardEmpty: {
    color: colors.textSecondary,
    fontSize: 14,
    paddingVertical: spacing.xl,
    textAlign: 'center',
  },
  forwardHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  forwardHeaderText: {
    flex: 1,
    gap: 2,
  },
  forwardName: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '800',
  },
  forwardPanel: {
    backgroundColor: colors.appBackground,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    elevation: 2,
    maxHeight: '78%',
    padding: spacing.lg,
    zIndex: 2,
  },
  forwardRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    paddingVertical: spacing.sm,
  },
  forwardRowText: {
    flex: 1,
  },
  forwardSectionTitle: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '900',
    marginBottom: spacing.xs,
    textTransform: 'uppercase',
  },
  forwardTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '900',
  },
  forwardSubtitle: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '700',
  },
  forwardUsername: {
    color: colors.textSecondary,
    fontSize: 13,
    marginTop: 2,
  },
  fullPhotoBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.94)',
    flex: 1,
    justifyContent: 'center',
    padding: spacing.lg,
  },
  fullPhotoClose: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    position: 'absolute',
    right: spacing.lg,
    top: spacing.xl,
    width: 44,
  },
  fullPhotoImage: {
    height: '82%',
    width: '100%',
  },
  hiddenList: {
    opacity: 0,
  },
  adminBadge: {
    alignItems: 'center',
    backgroundColor: colors.outgoingBubble,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 4,
    paddingHorizontal: spacing.xs,
    paddingVertical: 4,
  },
  adminBadgeText: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: '900',
  },
  chatGalleryEmpty: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: '700',
    paddingVertical: spacing.lg,
    textAlign: 'center',
  },
  chatGalleryFileIcon: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  chatGalleryFileMeta: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 2,
  },
  chatGalleryFileName: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '900',
  },
  chatGalleryFileRow: {
    alignItems: 'center',
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.sm,
    minHeight: 56,
    paddingVertical: spacing.sm,
  },
  chatGalleryFileText: {
    flex: 1,
    minWidth: 0,
  },
  chatGalleryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 2,
    width: '100%',
  },
  chatGalleryLinkRow: {
    alignItems: 'center',
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.sm,
    minHeight: 62,
    paddingVertical: spacing.sm,
  },
  chatGalleryLinkUrl: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 2,
  },
  chatGalleryList: {
    width: '100%',
  },
  chatGalleryMediaImage: {
    height: '100%',
    width: '100%',
  },
  chatGalleryOpenButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.md,
    marginTop: spacing.lg,
    minHeight: 58,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    width: '100%',
  },
  chatGalleryOpenIcon: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  chatGalleryOpenSubtitle: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '700',
    marginTop: 2,
  },
  chatGalleryOpenText: {
    flex: 1,
    minWidth: 0,
  },
  chatGalleryOpenTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '900',
  },
  chatGalleryMediaTile: {
    aspectRatio: 1,
    backgroundColor: colors.surface,
    overflow: 'hidden',
    position: 'relative',
    width: '32.9%',
  },
  chatGalleryPlayButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.52)',
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    left: '50%',
    marginLeft: -22,
    marginTop: -22,
    position: 'absolute',
    top: '50%',
    width: 44,
  },
  chatGalleryRowPressed: {
    backgroundColor: colors.surface,
  },
  chatGallerySection: {
    borderTopColor: colors.border,
    borderTopWidth: StyleSheet.hairlineWidth,
    gap: spacing.sm,
    marginTop: spacing.lg,
    paddingTop: spacing.md,
    width: '100%',
  },
  chatGalleryTab: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    flex: 1,
    flexDirection: 'row',
    gap: spacing.xs,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: spacing.sm,
  },
  chatGalleryTabActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  chatGalleryTabCount: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '900',
  },
  chatGalleryTabs: {
    flexDirection: 'row',
    gap: spacing.xs,
    width: '100%',
  },
  chatGalleryTabText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '900',
  },
  chatGalleryTabTextActive: {
    color: colors.white,
  },
  chatGalleryTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '900',
  },
  chatGalleryVideoFallback: {
    alignItems: 'center',
    backgroundColor: '#111827',
    height: '100%',
    justifyContent: 'center',
    width: '100%',
  },
  galleryModalBackButton: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  galleryModalContainer: {
    backgroundColor: colors.appBackground,
    flex: 1,
    paddingTop: spacing.xl,
  },
  galleryModalContent: {
    padding: spacing.lg,
    paddingBottom: spacing.xl,
  },
  galleryModalHeader: {
    alignItems: 'center',
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    minHeight: 56,
    paddingHorizontal: spacing.sm,
  },
  galleryModalHeaderSpacer: {
    width: 44,
  },
  galleryModalTitle: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  countdownActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'flex-end',
    marginTop: spacing.lg,
  },
  countdownBackdrop: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.55)',
    justifyContent: 'center',
    padding: spacing.xl,
  },
  countdownCancelButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: spacing.lg,
  },
  countdownCancelText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '800',
  },
  countdownConfirmButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 10,
    justifyContent: 'center',
    minHeight: 44,
    minWidth: 130,
    paddingHorizontal: spacing.lg,
  },
  countdownConfirmButtonDestructive: {
    backgroundColor: colors.danger,
  },
  countdownConfirmButtonDisabled: {
    opacity: 0.45,
  },
  countdownConfirmText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '900',
  },
  countdownInlineOverlay: {
    ...StyleSheet.absoluteFillObject,
    elevation: 30,
    zIndex: 30,
  },
  countdownDescription: {
    color: colors.textSecondary,
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 21,
    marginTop: spacing.sm,
  },
  countdownPanel: {
    backgroundColor: colors.appBackground,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    maxWidth: 420,
    padding: spacing.xl,
    width: '100%',
  },
  countdownTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '900',
  },
  groupSettingLabel: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
  },
  groupSettingRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
    minHeight: 48,
    width: '100%',
  },
  groupAdminActionButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'center',
    minHeight: 42,
    width: 52,
  },
  groupAdminActionButtonDisabled: {
    opacity: 0.55,
  },
  groupAdminActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  groupAdminActionText: {
    color: colors.primary,
    flex: 1,
    fontSize: 14,
    fontWeight: '900',
  },
  groupAdminActionTextDisabled: {
    color: colors.textSecondary,
  },
  groupDeleteButton: {
    alignItems: 'center',
    borderColor: colors.danger,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'center',
    minHeight: 42,
    width: 52,
  },
  groupDeleteButtonText: {
    color: colors.danger,
    flex: 1,
    fontSize: 14,
    fontWeight: '900',
  },
  groupAliasActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  groupAliasButtonDisabled: {
    opacity: 0.52,
  },
  groupAliasEditor: {
    gap: spacing.sm,
    width: '100%',
  },
  groupAliasInput: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    color: colors.textPrimary,
    fontSize: 15,
    minHeight: 42,
    paddingHorizontal: spacing.md,
  },
  groupAliasPrimaryButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: spacing.md,
  },
  groupAliasPrimaryText: {
    color: colors.white,
    fontSize: 13,
    fontWeight: '900',
  },
  groupAliasPrompt: {
    backgroundColor: colors.surface,
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    gap: spacing.sm,
    padding: spacing.md,
  },
  groupAliasPromptText: {
    gap: 2,
  },
  groupAliasSecondaryButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: spacing.md,
  },
  groupAliasSecondaryText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '900',
  },
  groupAliasSubtitle: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '700',
  },
  groupAliasTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '900',
  },
  groupSettingsSection: {
    borderTopColor: colors.border,
    borderTopWidth: StyleSheet.hairlineWidth,
    marginTop: spacing.lg,
    paddingTop: spacing.md,
    width: '100%',
  },
  groupSettingsTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '900',
    marginBottom: spacing.xs,
  },
  directChatSettingsSection: {
    borderTopColor: colors.border,
    borderTopWidth: StyleSheet.hairlineWidth,
    marginTop: spacing.md,
    paddingTop: spacing.sm,
    width: '100%',
  },
  directChatSettingText: {
    flex: 1,
    gap: 3,
  },
  directChatSettingLabel: {
    color: colors.textPrimary,
    flexShrink: 1,
    fontSize: 15,
    fontWeight: '800',
  },
  directChatSettingTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  directChatSettingHint: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 16,
  },
  compactToggle: {
    alignSelf: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 15,
    borderWidth: 1,
    flexShrink: 0,
    height: 30,
    justifyContent: 'center',
    paddingHorizontal: 3,
    width: 52,
  },
  compactToggleDisabled: {
    opacity: 0.55,
  },
  compactToggleEnabled: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  compactToggleThumb: {
    backgroundColor: colors.white,
    borderRadius: 11,
    height: 22,
    width: 22,
  },
  compactToggleThumbEnabled: {
    alignSelf: 'flex-end',
  },
  disappearingHeaderAvatar: {
    borderColor: colors.primary,
    borderRadius: 21,
    borderWidth: 1.5,
    padding: 2,
  },
  disappearingHeaderClock: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 9,
    bottom: -3,
    height: 17,
    justifyContent: 'center',
    position: 'absolute',
    right: -5,
    width: 17,
  },
  disappearingMessagesBadge: {
    backgroundColor: colors.primary,
    borderRadius: 10,
    color: colors.white,
    fontSize: 10,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: spacing.xs,
    paddingVertical: 2,
  },
  disappearingMessagesNotice: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  disappearingMessagesNoticeText: {
    color: colors.textSecondary,
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  groupLinkBox: {
    gap: spacing.xs,
    marginBottom: spacing.sm,
    marginTop: spacing.xs,
  },
  groupLinkInput: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
  },
  groupLinkInputWrap: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.sm,
    minHeight: 44,
    paddingHorizontal: spacing.md,
  },
  groupLinkLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '800',
  },
  infoAction: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    flex: 1,
    gap: spacing.sm,
    justifyContent: 'center',
    minHeight: 112,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.lg,
  },
  infoActionIconWrap: {
    alignItems: 'center',
    backgroundColor: colors.appBackground,
    borderRadius: 26,
    height: 52,
    justifyContent: 'center',
    width: 52,
  },
  infoActionText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 18,
    textAlign: 'center',
    width: '100%',
  },
  optionPickerDescription: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    marginBottom: spacing.xs,
  },
  infoActions: {
    alignSelf: 'stretch',
    flexDirection: 'row',
    gap: spacing.lg,
    marginTop: spacing.lg,
    justifyContent: 'space-between',
    width: '100%',
  },
  infoBackdrop: {
    backgroundColor: 'rgba(0,0,0,0.32)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  infoContent: {
    alignItems: 'center',
    gap: spacing.sm,
  },
  infoPanel: {
    alignItems: 'center',
    backgroundColor: colors.appBackground,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    elevation: 2,
    gap: spacing.sm,
    maxHeight: '86%',
    padding: spacing.xl,
    zIndex: 2,
  },
  infoAvatarButton: {
    position: 'relative',
  },
  infoAvatarCamera: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.42)',
    borderColor: 'rgba(255,255,255,0.55)',
    borderRadius: 17,
    borderWidth: StyleSheet.hairlineWidth,
    bottom: 2,
    height: 34,
    justifyContent: 'center',
    position: 'absolute',
    right: 2,
    width: 34,
  },
  infoEditButton: {
    alignItems: 'center',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    minHeight: 36,
    width: 36,
  },
  infoSubtitle: {
    color: colors.textSecondary,
    fontSize: 15,
  },
  infoTitle: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: 22,
    fontWeight: '900',
    textAlign: 'center',
  },
  infoTitleInput: {
    borderBottomColor: colors.primary,
    borderBottomWidth: 1,
    color: colors.textPrimary,
    flex: 1,
    fontSize: 20,
    fontWeight: '900',
    minHeight: 42,
    paddingHorizontal: spacing.xs,
    textAlign: 'center',
  },
  infoTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 1,
    justifyContent: 'center',
    width: '100%',
  },
  input: {
    backgroundColor: colors.surface,
    borderRadius: 22,
    color: colors.textPrimary,
    fontSize: 16,
    maxHeight: 120,
    minHeight: 44,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  inputFlex: {
    flex: 1,
  },
  holdRecordingInput: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: spacing.lg,
  },
  holdRecordingText: {
    color: colors.danger,
    fontSize: 16,
    fontWeight: '900',
  },
  inputInWrap: {
    borderRadius: 0,
  },
  inputWrap: {
    backgroundColor: colors.surface,
    borderRadius: 22,
    flex: 1,
    overflow: 'hidden',
  },
  list: {
    flex: 1,
  },
  dateDividerPill: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: spacing.md,
    paddingVertical: 5,
  },
  dateDividerRow: {
    alignItems: 'center',
    marginBottom: spacing.sm,
    marginTop: spacing.sm,
  },
  dateDividerText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '800',
  },
  messageList: {
    flexGrow: 1,
    justifyContent: 'flex-end',
    padding: spacing.md,
    paddingBottom: spacing.lg,
  },
  invertedMessageList: {
    justifyContent: 'flex-start',
    paddingBottom: spacing.md,
  },
  messageCheckbox: {
    alignItems: 'center',
    alignSelf: 'center',
    height: 42,
    justifyContent: 'center',
    width: 34,
  },
  memberName: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '800',
  },
  memberPendingBadge: {
    backgroundColor: colors.appBackground,
    borderColor: colors.border,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
  },
  memberPendingBadgeText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: '900',
  },
  memberRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    paddingVertical: spacing.sm,
    width: '100%',
  },
  memberRowPressed: {
    backgroundColor: colors.surface,
  },
  memberSection: {
    borderTopColor: colors.border,
    borderTopWidth: StyleSheet.hairlineWidth,
    marginTop: spacing.lg,
    paddingTop: spacing.md,
    width: '100%',
  },
  memberSectionCount: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '700',
  },
  memberSectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.xs,
    width: '100%',
  },
  memberSectionTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '900',
  },
  memberHiddenText: {
    color: colors.textSecondary,
    fontSize: 14,
    paddingVertical: spacing.md,
    textAlign: 'center',
  },
  memberAddButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    height: 36,
    justifyContent: 'center',
    minHeight: 36,
    width: 36,
  },
  memberHeaderActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.xs,
  },
  memberListPane: {
    borderColor: colors.border,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    maxHeight: 320,
    minHeight: 96,
    overflow: 'hidden',
    paddingHorizontal: spacing.sm,
    width: '100%',
  },
  memberPageButton: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 2,
    minHeight: 34,
    paddingHorizontal: spacing.xs,
  },
  memberPageButtonDisabled: {
    opacity: 0.45,
  },
  memberPageButtonText: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '900',
  },
  memberPageButtonTextDisabled: {
    color: colors.textSecondary,
  },
  memberPageEllipsis: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '900',
    paddingHorizontal: 2,
  },
  memberPageNumber: {
    alignItems: 'center',
    borderRadius: 14,
    height: 28,
    justifyContent: 'center',
    minWidth: 28,
    paddingHorizontal: spacing.xs,
  },
  memberPageNumberActive: {
    backgroundColor: colors.primary,
  },
  memberPageNumbers: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 1,
    gap: 2,
    justifyContent: 'center',
  },
  memberPageNumberText: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: '900',
  },
  memberPageNumberTextActive: {
    color: colors.white,
  },
  memberPageSummary: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
  },
  memberPagination: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.xs,
    justifyContent: 'space-between',
    paddingTop: spacing.sm,
    width: '100%',
  },
  memberText: {
    flex: 1,
  },
  memberSearchButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  memberSearchHint: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
    width: '100%',
  },
  memberSearchInput: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: 15,
    minHeight: 40,
    padding: 0,
  },
  memberSearchWrap: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    width: '100%',
  },
  modalSearchHint: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
    marginBottom: spacing.sm,
  },
  modalSearchInput: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: 15,
    minHeight: 40,
    padding: 0,
  },
  modalSearchWrap: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.sm,
    paddingHorizontal: spacing.md,
    width: '100%',
  },
  memberUsername: {
    color: colors.textSecondary,
    fontSize: 13,
    marginTop: 2,
  },
  recordingBar: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.sm,
    marginHorizontal: spacing.sm,
    padding: spacing.md,
  },
  recordingBarLocked: {
    borderColor: colors.primary,
  },
  recordingButton: {
    backgroundColor: colors.danger,
  },
  micButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 1.06 }],
  },
  recordingDot: {
    backgroundColor: colors.danger,
    borderRadius: 5,
    height: 10,
    width: 10,
  },
  recordingTime: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '800',
  },
  scrollToBottomButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 22,
    elevation: 4,
    height: 44,
    justifyContent: 'center',
    position: 'absolute',
    right: spacing.md,
    shadowColor: '#000',
    shadowOffset: { height: 2, width: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    width: 44,
    zIndex: 12,
  },
  recordingLockHint: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 3,
  },
  recordingLockHintText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  lockedVoiceActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.xs,
  },
  lockedVoiceButton: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 22,
    borderWidth: StyleSheet.hairlineWidth,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  lockedVoiceDeleteButton: {
    borderColor: colors.danger,
  },
  pendingVoiceActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  pendingVoiceBar: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    minHeight: 44,
    paddingHorizontal: spacing.sm,
  },
  pendingVoiceDiscardButton: {
    alignItems: 'center',
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  pendingVoiceGearButton: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 22,
    borderWidth: StyleSheet.hairlineWidth,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  pendingVoiceSubtitle: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 2,
  },
  pendingVoiceText: {
    flex: 1,
    minWidth: 0,
  },
  pendingVoiceTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '800',
  },
  readOnlyComposer: {
    alignItems: 'center',
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
  },
  readOnlyComposerText: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: '800',
  },
  selectableMessageBubble: {
    flex: 1,
  },
  selectableMessageRow: {
    alignItems: 'stretch',
    flexDirection: 'row',
    gap: spacing.xs,
    width: '100%',
  },
  screen: {
    backgroundColor: colors.chatBackground,
    flex: 1,
  },
  sendButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 24,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  sendButtonDisabled: {
    backgroundColor: colors.border,
  },
  searchBar: {
    alignItems: 'center',
    backgroundColor: colors.appBackground,
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  searchButton: {
    alignItems: 'center',
    height: 36,
    justifyContent: 'center',
    width: 34,
  },
  searchCount: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '800',
    minWidth: 42,
    textAlign: 'center',
  },
  searchInput: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    color: colors.textPrimary,
    flex: 1,
    fontSize: 15,
    height: 38,
    paddingHorizontal: spacing.md,
  },
  subscriberCheckbox: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: 11,
    borderWidth: 2,
    height: 22,
    justifyContent: 'center',
    width: 22,
  },
  subscriberCheckboxSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  viewer: {
    alignItems: 'center',
    backgroundColor: '#000000',
    flex: 1,
    justifyContent: 'center',
  },
  viewerRoot: {
    backgroundColor: '#000000',
    flex: 1,
  },
  viewerClose: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.46)',
    borderRadius: 26,
    height: 52,
    justifyContent: 'center',
    left: spacing.md,
    position: 'absolute',
    top: spacing.xl,
    width: 52,
    zIndex: 1,
  },
  viewerCounter: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.46)',
    borderRadius: 16,
    paddingHorizontal: spacing.md,
    paddingVertical: 7,
    position: 'absolute',
    top: spacing.xl + 8,
    zIndex: 1,
  },
  viewerCounterText: {
    color: colors.white,
    fontSize: 13,
    fontWeight: '800',
  },
  viewerError: {
    color: colors.white,
    fontSize: 15,
    fontWeight: '700',
    paddingHorizontal: spacing.xl,
    textAlign: 'center',
  },
  viewerImage: {
    height: '100%',
    width: '100%',
  },
  viewerPager: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'hidden',
  },
  viewerPagerCoverImage: {
    ...StyleSheet.absoluteFillObject,
    height: '100%',
    width: '100%',
    zIndex: 2,
  },
  viewerPagerImage: {
    ...StyleSheet.absoluteFillObject,
    height: '100%',
    width: '100%',
  },
  viewerVideo: {
    height: '100%',
    width: '100%',
  },
});
}


export let chatRoomStyles = createChatRoomStyles();

export function refreshChatRoomStyles() {
  chatRoomStyles = createChatRoomStyles();
  return chatRoomStyles;
}
