import { StyleSheet } from 'react-native';

import { colors } from '../../theme/colors';
import { spacing } from '../../theme/spacing';

const LOCAL_PREVIEW_HEIGHT = 132;
const LOCAL_PREVIEW_WIDTH = 96;
const LOCAL_PREVIEW_CONTROLS_CLEARANCE = 104;
const LOCAL_PREVIEW_EDGE_MARGIN = 16;
const MINI_CALL_WIDTH = 132;
const MINI_CALL_HEIGHT = 178;

export function createCallRoomStyles() {
  return StyleSheet.create({
  addPeopleHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  addPeoplePanel: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    gap: spacing.md,
    height: '86%',
    maxHeight: '86%',
    padding: spacing.lg,
  },
  addPeopleTitle: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: '800',
  },
  allPeopleButton: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderRadius: 18,
    flexDirection: 'row',
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  allPeopleText: {
    color: colors.white,
    fontSize: 13,
    fontWeight: '800',
  },
  answerButton: {
    backgroundColor: '#18b85f',
  },
  hiddenScreenCapturePicker: {
    height: 1,
    opacity: 0,
    position: 'absolute',
    width: 1,
  },
  controlActive: {
    backgroundColor: 'rgba(0,0,0,0.42)',
  },
  controlButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderRadius: 20,
    gap: spacing.xs,
    height: 60,
    justifyContent: 'center',
    width: 60,
  },
  callContent: {
    alignSelf: 'stretch',
    flex: 1,
    justifyContent: 'space-between',
  },
  callMenuBackdrop: {
    alignItems: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.28)',
    flex: 1,
    paddingHorizontal: spacing.md,
    paddingTop: 76,
  },
  callTopMenuItem: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    minHeight: 48,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  callTopMenuItemDisabled: {
    opacity: 0.55,
  },
  callTopMenuPanel: {
    backgroundColor: 'rgba(7, 13, 24, 0.96)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 14,
    borderWidth: 1,
    maxWidth: 280,
    minWidth: 210,
    overflow: 'hidden',
  },
  callTopMenuText: {
    color: colors.white,
    flexShrink: 1,
    fontSize: 15,
    fontWeight: '800',
  },
  compactVoiceCall: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    flex: 1,
    gap: spacing.sm,
    justifyContent: 'center',
    width: '100%',
  },
  compactVoiceText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '800',
  },
  connectionEndButton: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: colors.danger,
    borderRadius: 18,
    justifyContent: 'center',
    height: 36,
    width: 36,
  },
  connectionEndText: {
    color: colors.white,
    fontSize: 15,
    fontWeight: '900',
  },
  connectionIconWrap: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  connectionModalMessage: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 12,
    fontWeight: '700',
  },
  connectionModalPanel: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(7, 13, 24, 0.96)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.sm,
    left: spacing.md,
    maxWidth: 460,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    position: 'absolute',
    right: spacing.md,
  },
  connectionModalShade: {
    ...StyleSheet.absoluteFillObject,
    flex: 1,
    zIndex: 45,
  },
  connectionModalText: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  connectionModalTitle: {
    color: colors.white,
    fontSize: 13,
    fontWeight: '900',
  },
  connectionProgressRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.xs,
  },
  connectionProgressText: {
    color: 'rgba(255,255,255,0.82)',
    flex: 1,
    fontSize: 11,
    fontWeight: '800',
  },
  waitingCallActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginLeft: spacing.md,
  },
  waitingCallBanner: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(7, 13, 24, 0.96)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    left: spacing.md,
    maxWidth: 460,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    position: 'absolute',
    right: spacing.md,
  },
  waitingCallBannerText: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
  },
  waitingCallIconWrap: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  waitingCallMessage: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 12,
    lineHeight: 16,
  },
  waitingCallMessageWrap: {
    flex: 1,
    marginLeft: spacing.sm,
    marginRight: spacing.sm,
  },
  waitingCallOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 40,
  },
  waitingCallPrimaryButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 18,
    justifyContent: 'center',
    height: 36,
    width: 36,
  },
  waitingCallSecondaryButton: {
    alignItems: 'center',
    backgroundColor: colors.danger,
    borderRadius: 18,
    justifyContent: 'center',
    height: 36,
    width: 36,
  },
  waitingCallTitle: {
    color: colors.white,
    fontSize: 13,
    fontWeight: '800',
  },
  controlLabel: {
    color: colors.white,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 11,
    textAlign: 'center',
    width: 56,
  },
  controls: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.xs,
    justifyContent: 'center',
  },
  declineButton: {
    backgroundColor: colors.danger,
  },
  declineIcon: {
    transform: [{ rotate: '135deg' }],
  },
  encryptionText: {
    color: '#d9f3ee',
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  endButton: {
    alignItems: 'center',
    backgroundColor: colors.danger,
    borderRadius: 28,
    height: 56,
    justifyContent: 'center',
    transform: [{ rotate: '135deg' }],
    width: 56,
  },
  incomingActionText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: '800',
    marginTop: spacing.xs,
  },
  incomingControls: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
  },
  incomingControlsWrap: {
    alignItems: 'center',
    alignSelf: 'stretch',
    gap: spacing.md,
    paddingHorizontal: spacing.xl,
  },
  incomingScreen: {
    backgroundColor: '#021817',
  },
  incomingStage: {
    backgroundColor: '#021817',
    borderRadius: 28,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xl,
  },
  incomingVideoShade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.46)',
    zIndex: 1,
  },
  incomingVoiceChangerButton: {
    alignItems: 'center',
    backgroundColor: '#f59e0b',
    borderRadius: 34,
    gap: 2,
    height: 68,
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
    width: 68,
  },
  incomingVoiceChangerButtonLocked: {
    backgroundColor: 'rgba(148,163,184,0.88)',
  },
  incomingVoiceChangerText: {
    color: colors.white,
    fontSize: 8,
    fontWeight: '900',
    lineHeight: 9,
    textAlign: 'center',
    width: 58,
  },
  incomingVoiceEffectActions: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  incomingVoiceEffectList: {
    gap: spacing.sm,
  },
  incomingVoiceEffectOption: {
    alignItems: 'center',
    backgroundColor: colors.appBackground,
    borderRadius: 18,
    flexDirection: 'row',
    gap: spacing.sm,
    padding: spacing.md,
  },
  incomingVoiceEffectOptionDescription: {
    color: colors.mutedText,
    fontSize: 12,
    fontWeight: '700',
  },
  incomingVoiceEffectOptionDescriptionSelected: {
    color: 'rgba(255,255,255,0.82)',
  },
  incomingVoiceEffectOptionIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(66,153,225,0.16)',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  incomingVoiceEffectOptionSelected: {
    backgroundColor: colors.primary,
  },
  incomingVoiceEffectOptionText: {
    flex: 1,
    minWidth: 0,
  },
  incomingVoiceEffectOptionTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '900',
  },
  incomingVoiceEffectOptionTitleSelected: {
    color: colors.white,
  },
  incomingVoiceEffectPanel: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    gap: spacing.md,
    padding: spacing.lg,
  },
  incomingVoiceEffectPrimaryButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 16,
    flex: 1,
    justifyContent: 'center',
    minHeight: 48,
  },
  incomingVoiceEffectPrimaryButtonDisabled: {
    opacity: 0.72,
  },
  incomingVoiceEffectPrimaryText: {
    color: colors.white,
    fontSize: 15,
    fontWeight: '900',
  },
  incomingVoiceEffectSecondaryButton: {
    alignItems: 'center',
    backgroundColor: colors.appBackground,
    borderRadius: 16,
    flex: 1,
    justifyContent: 'center',
    minHeight: 48,
  },
  incomingVoiceEffectSecondaryText: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '900',
  },
  incomingVoiceEffectSubtitle: {
    color: colors.mutedText,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  incomingVoiceEffectTitle: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: '900',
  },
  localPreview: {
    backgroundColor: '#0b3d38',
    borderColor: 'rgba(255,255,255,0.72)',
    borderRadius: 14,
    borderWidth: 1,
    bottom: LOCAL_PREVIEW_CONTROLS_CLEARANCE,
    height: LOCAL_PREVIEW_HEIGHT,
    overflow: 'hidden',
    position: 'absolute',
    right: LOCAL_PREVIEW_EDGE_MARGIN,
    width: LOCAL_PREVIEW_WIDTH,
    zIndex: 2,
  },
  localPreviewOff: {
    alignItems: 'center',
    gap: spacing.xs,
    justifyContent: 'center',
  },
  localPreviewText: {
    color: colors.white,
    fontSize: 11,
    fontWeight: '800',
  },
  localPreviewTextContainer: {
    backgroundColor: 'rgba(0,0,0,0.6)',
    bottom: 0,
    left: 0,
    padding: 4,
    position: 'absolute',
    right: 0,
  },
  localVideo: {
    height: '100%',
    width: '100%',
  },
  localVideoKeepAlive: {
    height: 1,
    left: -2,
    opacity: 0,
    position: 'absolute',
    top: -2,
    width: 1,
  },
  localCameraPreview: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#062d29',
  },
  localCameraPreviewFallback: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    backgroundColor: '#062d29',
    justifyContent: 'center',
  },
  localCameraPreviewShade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.18)',
  },
  localCameraPreviewVideo: {
    ...StyleSheet.absoluteFillObject,
  },
  modalCloseButton: {
    alignItems: 'center',
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  modalList: {
    flex: 1,
  },
  modalShade: {
    backgroundColor: 'rgba(0,0,0,0.42)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  name: {
    color: colors.white,
    fontSize: 30,
    fontWeight: '800',
  },
  noPeopleText: {
    color: colors.textSecondary,
    fontSize: 15,
    padding: spacing.lg,
    textAlign: 'center',
  },
  miniCallBox: {
    backgroundColor: colors.chatHeader,
    borderColor: 'rgba(255,255,255,0.42)',
    borderRadius: 14,
    borderWidth: 1,
    height: MINI_CALL_HEIGHT,
    overflow: 'hidden',
    position: 'absolute',
    width: MINI_CALL_WIDTH,
    zIndex: 12,
  },
  miniCallPressable: {
    flex: 1,
  },
  miniCallLabel: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.52)',
    bottom: 0,
    flexDirection: 'row',
    gap: 4,
    left: 0,
    paddingHorizontal: spacing.xs,
    paddingVertical: 5,
    position: 'absolute',
    right: 0,
  },
  miniCallLabelText: {
    color: colors.white,
    flex: 1,
    fontSize: 11,
    fontWeight: '800',
  },
  miniChatLast: {
    color: colors.textSecondary,
    fontSize: 13,
    marginTop: 2,
  },
  miniChatRow: {
    alignItems: 'center',
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  miniChatRowPressed: {
    backgroundColor: colors.surface,
  },
  miniChatsHeader: {
    backgroundColor: colors.chatHeader,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.md,
    paddingTop: spacing.xl,
  },
  miniChatsList: {
    paddingBottom: 220,
  },
  miniChatsTitle: {
    color: colors.white,
    fontSize: 22,
    fontWeight: '900',
  },
  miniChatText: {
    flex: 1,
  },
  miniChatTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '900',
  },
  minimizedCallOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  minimizedAppScreen: {
    backgroundColor: colors.appBackground,
    flex: 1,
  },
  minimizedCallLayer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'transparent',
  },
  liveKitRoomHost: {
    flex: 1,
  },
  miniUnreadBadge: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 11,
    minWidth: 22,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  miniUnreadText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: '900',
  },
  overlayControls: {
    left: 0,
    paddingHorizontal: spacing.sm,
    position: 'absolute',
    right: 0,
    zIndex: 3,
  },
  overlayTopBar: {
    backgroundColor: 'rgba(0,0,0,0.22)',
    left: 0,
    paddingBottom: spacing.sm,
    paddingHorizontal: spacing.md,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 3,
  },
  peopleSearchInput: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: 16,
    minHeight: 42,
    padding: 0,
  },
  peopleSearchWrap: {
    alignItems: 'center',
    backgroundColor: colors.appBackground,
    borderRadius: 20,
    flexDirection: 'row',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  personName: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '800',
  },
  personRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    paddingVertical: spacing.sm,
  },
  personText: {
    flex: 1,
    gap: 2,
  },
  personUsername: {
    color: colors.textSecondary,
    fontSize: 13,
  },
  participantLine: {
    color: 'rgba(255,255,255,0.88)',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 21,
    maxWidth: '88%',
    textAlign: 'center',
  },
  pipOnlyStage: {
    flex: 1,
  },
  pipScreen: {
    justifyContent: 'center',
    paddingBottom: 0,
    paddingHorizontal: 0,
    paddingTop: 0,
  },
  roundCallButton: {
    alignItems: 'center',
    borderRadius: 38,
    height: 76,
    justifyContent: 'center',
    width: 76,
  },
  screen: {
    backgroundColor: colors.chatHeader,
    flex: 1,
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
  },
  stage: {
    alignItems: 'center',
    gap: spacing.md,
  },
  status: {
    color: '#d9f3ee',
    fontSize: 16,
    fontWeight: '700',
  },
  topBar: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  topActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.xs,
  },
  topButton: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  remotePlaceholder: {
    alignItems: 'center',
    backgroundColor: '#0b3d38',
    flex: 1,
    gap: spacing.md,
    justifyContent: 'center',
  },
  remotePlaceholderCompact: {
    gap: 0,
  },
  remoteVideo: {
    height: '100%',
    width: '100%',
  },
  videoGridStage: {
    alignContent: 'stretch',
    alignSelf: 'stretch',
    backgroundColor: '#062d29',
    borderRadius: 0,
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 2,
    height: '100%',
    overflow: 'hidden',
  },
  videoCallSubtitle: {
    color: 'rgba(255,255,255,0.86)',
    fontSize: 13,
    fontWeight: '800',
  },
  videoCallTitle: {
    color: colors.white,
    fontSize: 17,
    fontWeight: '900',
  },
  videoNamePill: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.48)',
    borderRadius: 12,
    bottom: spacing.sm,
    flexDirection: 'row',
    gap: spacing.xs,
    left: spacing.sm,
    maxWidth: '80%',
    paddingHorizontal: 4,
    paddingVertical: 3,
    position: 'absolute',
  },
  videoNameText: {
    color: colors.white,
    fontSize: 11,
    fontWeight: '800',
  },
  videoStageCompact: {
    borderRadius: 0,
    flex: 1,
    height: undefined,
  },
  videoScreen: {
    justifyContent: 'center',
    paddingBottom: 0,
    paddingHorizontal: 0,
    paddingTop: 0,
  },
  videoStageFull: {
    ...StyleSheet.absoluteFillObject,
  },
  systemPipScreen: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#062d29',
    overflow: 'hidden',
  },
  systemPipStage: {
    alignSelf: 'stretch',
    backgroundColor: '#062d29',
    flex: 1,
    overflow: 'hidden',
    width: '100%',
  },
  systemPipLabel: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.44)',
    bottom: 0,
    flexDirection: 'row',
    gap: 4,
    left: 0,
    paddingHorizontal: spacing.xs,
    paddingVertical: 4,
    position: 'absolute',
    right: 0,
  },
  systemPipLabelText: {
    color: colors.white,
    flex: 1,
    fontSize: 12,
    fontWeight: '900',
  },
  systemVoicePipStage: {
    flex: 1,
    width: '100%',
  },
  systemVideoPipStage: {
    flex: 1,
    width: '100%',
  },
  videoStatusOverlay: {
    backgroundColor: 'rgba(0,0,0,0.42)',
    borderRadius: 18,
    left: spacing.md,
    maxWidth: '68%',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    position: 'absolute',
    top: 102,
  },
  videoTile: {
    backgroundColor: '#0b3d38',
    overflow: 'hidden',
  },
  videoTileFour: {
    height: '50%',
    width: '49.7%',
  },
  videoTileOne: {
    height: '100%',
    width: '100%',
  },
  videoTileSix: {
    height: '33.1%',
    width: '49.7%',
  },
  videoTileTwo: {
    height: '100%',
    width: '49.7%',
  },
  videoWaitingText: {
    color: colors.white,
    fontSize: 15,
    fontWeight: '800',
  },
  voiceEffectBackdrop: {
    backgroundColor: 'rgba(0,0,0,0.48)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  voiceGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    justifyContent: 'center',
  },
  voiceGroupStage: {
    alignSelf: 'stretch',
    gap: spacing.lg,
    justifyContent: 'center',
    minHeight: 260,
  },
  voiceTile: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 16,
    gap: spacing.sm,
    padding: spacing.md,
    width: '30%',
  },
  voiceTileName: {
    color: colors.white,
    fontSize: 12,
    fontWeight: '800',
    maxWidth: '100%',
  },
});
}
